services:
  sheva-prodamus-tg-bot:
    container_name: "sheva-prodamus-tg-bot"
    build: ./
    command: sh -c "python main.py"
    env_file:
      - .env
    depends_on:
      - sheva-prodamus-postgresdb
    environment:
        TELEGRAM_API_BASE: "http://5.129.230.89:8098"

  sheva-prodamus-nginx:
    container_name: "sheva-prodamus-nginx"
    build: ./nginx
    restart: on-failure
    depends_on:
      - sheva-prodamus-api
    ports:
      - 8081:80

  sheva-prodamus-api:
    container_name: "sheva-prodamus-api"
    build: ./server
    image: sheva-prodamus-api:20260922-security
    depends_on:
      - sheva-prodamus-postgresdb
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      TELEGRAM_API_BASE: "http://5.129.230.89:8098"
    volumes:
      - ./logs:/app/logs/

  sheva-prodamus-postgresdb:
    image: postgres:13.1
    restart: always
    volumes:
      - ./custom-pg_hba.conf:/etc/postgresql/pg_hba.conf
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - 5433:5432
    command: postgres -c hba_file=/etc/postgresql/pg_hba.conf

volumes:
  postgres_data:
