services:
#  bot:
#    container_name: "bot"
#    build: ./
#    command: sh -c "python main.py"
#    env_file:
#      - .env
#    depends_on:
#      - postgresdb

#  nginx:
#    container_name: "nginx"
#    build: ./nginx
#    restart: on-failure
#    depends_on:
#      - api
#    ports:
#      - 80:80

  api:
    container_name: "api"
    build: ./server
    depends_on:
      - postgresdb
    ports:
      - 8000:8000

  postgresdb:
    image: postgres:13.1
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - 5432:5432

  ngrok:
    image: ngrok/ngrok:alpine
    environment:
      NGROK_AUTHTOKEN: '...'
    command: 'http --url=heron-settled-centrally.ngrok-free.app http://localhost:8000'
    ports:
      - '80:80'
    expose:
      - '80'

volumes:
  postgres_data:
