services:
  sheva-prodamus-tg-bot:
    container_name: "sheva-prodamus-tg-bot"
    build: ./
    command: sh -c "python main.py"
    env_file:
      - .env
    depends_on:
      - sheva-prodamus-postgresdb

  sheva-prodamus-nginx:
    container_name: "sheva-prodamus-nginx"
    build: ./nginx
    restart: on-failure
    depends_on:
      - sheva-prodamus-api
    ports:
      - 80:80

  sheva-prodamus-api:
    container_name: "sheva-prodamus-api"
    build: ./server
    depends_on:
      - sheva-prodamus-postgresdb
    ports:
      - 8000:8000
    volumes:
      - ./logs:/app/logs/

  sheva-prodamus-postgresdb:
    image: postgres:13.1
    restart: always
    volumes:
      - ./custom-pg_hba.conf:/etc/postgresql/pg_hba.conf
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - 5433:5433
    command: postgres -c hba_file=/etc/postgresql/pg_hba.conf

volumes:
  postgres_data:
