services:
  bot:
    container_name: "bot"
    build: ./
    command: sh -c "python main.py"
    env_file:
      - .env
    depends_on:
      - postgresdb

  nginx:
    container_name: "nginx"
    build: ./nginx
    restart: on-failure
    depends_on:
      - server
    ports:
      - 80:80

  server:
    container_name: "server"
    build: ./server/
    depends_on:
      - postgresdb
    ports:
      - 8000:8000

  postgresdb:
    image: postgres:13.1
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - 5434:5432

volumes:
  postgres_data: