"""add_trial

Revision ID: c8ec2683d4f3
Revises: c3ebf2be1dbd
Create Date: 2025-09-18 18:02:53.992242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8ec2683d4f3'
down_revision: Union[str, None] = 'c3ebf2be1dbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('trial_used', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'trial_used')
    # ### end Alembic commands ###
